### ISSUE TITLE
No longer works on Flipper 0.115.0

### ISSUE THREAD

**Issue by chungweileong94** [infinitered/flipper-plugin-reactotron#77]
For some reason, nothing works in the latest Flipper

It does log an error,
```
Failed to process event for plugin flipper-plugin-reactotron TypeError: Cannot assign to read only property 'path' of object '#<Object>'
```

**Comment by alexstanbury** [comment]
Same issue here, here's a full stack trace from the logs:

```
Failed to process event for plugin flipper-plugin-reactotron TypeError: Cannot assign to read only property 'important' of object '#<Object>'
    at t (/Users/alexstanbury/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js:4618:53)

    at repairSerialization (/Users/alexstanbury/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js:4622:39)

    at Function.persistedStateReducer (/Users/alexstanbury/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js:821:74)

    at EventEmitter.<anonymous> (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5915:1349)

    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1151:230

    at Wj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:98407)

    at EventEmitter.<anonymous> (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1151:219)

    at EventEmitter.emit (events.js:315:20)

    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1554:2100

    at Array.forEach (<anonymous>)

    at SandyPluginInstance.receiveMessages (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1554:1975)

    at processMessagesImmediately (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4224:349)

    at processMessagesLater (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4224:711)

    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4222:1402

    at Wj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:98407)

    at Client.flushMessageBuffer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4222:1335)```

**Comment by chungweileong94** [comment]
@alexstanbury I actually have a [temporary fix](https://github.com/infinitered/reactotron-core-ui/issues/750) for this, but you might need to dig into the bundle JS code and apply the changes.

Just to save you some time, I will attach the modified bundle JS😉. 

Just unzip it and put it under `~/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js`
[bundle.js.zip](https://github.com/infinitered/flipper-plugin-reactotron/files/7497552/bundle.js.zip)

**Comment by chungweileong94** [comment]
I'm curious if this project is still actively maintained? As the plugin is basically unusable.

**Comment by chungweileong94** [comment]
> @alexstanbury I actually have a [temporary fix](https://github.com/infinitered/reactotron-core-ui/issues/750) for this, but you might need to dig into the bundle JS code and apply the changes.
> 
> Just to save you some time, I will attach the modified bundle JS😉.
> 
> Just unzip it and put it under `~/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js` [bundle.js.zip](https://github.com/infinitered/flipper-plugin-reactotron/files/7497552/bundle.js.zip) (btw Github don't allow me to upload JS file, that's why I zip it)

Instead of modifying the bundle code, I applied the workaround fix and repackage on my fork. 
https://github.com/chungweileong94/flipper-plugin-reactotron/releases/tag/v1.1.0-custom-fix

**Comment by alexstanbury** [comment]
Thanks, it's working for me now. Hopefully this will get fixed properly!

**Comment by apatel369** [comment]
> > @alexstanbury I actually have a [temporary fix](https://github.com/infinitered/reactotron-core-ui/issues/750) for this, but you might need to dig into the bundle JS code and apply the changes.
> > Just to save you some time, I will attach the modified bundle JS😉.
> > Just unzip it and put it under `~/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js` [bundle.js.zip](https://github.com/infinitered/flipper-plugin-reactotron/files/7497552/bundle.js.zip) (btw Github don't allow me to upload JS file, that's why I zip it)
> 
> Instead of modifying the bundle code, I applied the workaround fix and repackage on my fork. https://github.com/chungweileong94/flipper-plugin-reactotron/releases/tag/v1.1.0-custom-fix

how to use custom fix?

**Comment by alessioemireni** [comment]
+1

**Comment by noumantahir** [comment]
> > @alexstanbury I actually have a [temporary fix](https://github.com/infinitered/reactotron-core-ui/issues/750) for this, but you might need to dig into the bundle JS code and apply the changes.
> > Just to save you some time, I will attach the modified bundle JSwink.
> > Just unzip it and put it under `~/.flipper/installed-plugins/flipper-plugin-reactotron/1.1.0/dist/bundle.js` [bundle.js.zip](https://github.com/infinitered/flipper-plugin-reactotron/files/7497552/bundle.js.zip) (btw Github don't allow me to upload JS file, that's why I zip it)
> 
> Instead of modifying the bundle code, I applied the workaround fix and repackage on my fork. https://github.com/chungweileong94/flipper-plugin-reactotron/releases/tag/v1.1.0-custom-fix

worked like a charm. Thanks
